In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
file = pd.read_csv('//Client/C$/Users/Hanne/Desktop/Data/manual_assay_annotation.txt',sep='\t')

In [3]:
file.head()

   accession assay_name pride_tissue cell_type tissue   status
0  PXD000004       HSE3    ['brain']     Brain  Brain  Healthy
1  PXD000004        HSA    ['brain']     Brain  Brain  Healthy
2  PXD000004       HSA3    ['brain']     Brain  Brain  Healthy
3  PXD000004        HSE    ['brain']     Brain  Brain  Healthy
4  PXD000004       HSB3    ['brain']     Brain  Brain  Healthy

In [4]:
file["accession"].nunique()

216

In [5]:
annotated_data = pd.read_csv("phospho_data_tissue_annotation.tsv", sep='\t')
annotated_data.head()

        proj         peptide modres  UP_POS  ACC_ID  pep_start  pep_end tissue
0  PXD000004      RPPSPEPSTK      S    2102  Q01082       2099     2108  Brain
1  PXD000004      ACVVHGSDLK      C     660  P50993        659      668  Brain
2  PXD000004      ACVVHGSDLK      C     663  P05023        662      671  Brain
3  PXD000004    AISPTSATSSGR      S     600  Q9Y4I1        598      609  Brain
4  PXD000004  FYYTAGSSSPTHAK      S     198  O75508        190      203  Brain

In [6]:
annotated_data.dropna(inplace=True)
annotated_data["proj"].nunique()

161

In [8]:
file[file["tissue"].isna()]

,accession,assay_name,pride_tissue,cell_type,tissue,status
168,PXD000440,HJ110112_IL2and15_E,['blood'],NaN,NaN,Cell culture
1468,PXD002132,HNSCC_TMT_pY1000_01,['head and neck squamous cell carcinoma cell l...,NaN,NaN,cancer
2745,PXD005650,Jurkat_Stimulated_TiO2_15cm_3um_Column_R2,['JURKAT cell'],NaN,NaN,Cell culture
2746,PXD005650,Jurkat_Stimulated_TiO2_50cm_3um_Column_R5,['JURKAT cell'],NaN,NaN,Cell culture
2747,PXD005650,Jurkat_Stimulated_TiO2_15cm_3um_Column_R5,['JURKAT cell'],NaN,NaN,Cell culture
...,...,...,...,...,...,...
13158,PXD011152,Set4_t21,['lymph node'],NaN,NaN,no distinct annotation
13159,PXD011152,Set4_t2,['lymph node'],NaN,NaN,no distinct annotation
13160,PXD011152,Set4_std_200ng,['lymph node'],NaN,NaN,no distinct annotation
13161,PXD011152,Set4_t12,['lymph node'],NaN,NaN,no distinct annotation
13162,PXD011152,Set4_t4,['lymph node'],NaN,NaN,no distinct annotation